- name: Test telegram module
  hosts: localhost
  connection: local
  tasks:
    - copy: src=/root/telegram/pruebatelegram dest=/root/telegram/modificado
      register: prueba
      ignore_errors: true
    - name: Mensaje de que funciona
      telegram:
        token: "TOKEN DE TU BOT DE TELEGRAM"
        chat_id: ID DEL CHAT EN EL QUE QUIERES QUE SE NOTIFIQUE
        msg: "Se ha modificado correctamente"
      when: prueba.changed

    - name: Mensaje de que no funciona
      telegram:
        token: "TOKEN DE TU BOT DE TELEGRAM"
        chat_id: ID DEL CHAT EN EL QUE QUIERES QUE SE NOTIFIQUE
        msg: "No se ha modificado"
      when: not prueba.changed
